name: chefxyz
root: tmp
category: srv
server: http
layout:
  adapter:
    name: adapter
    type: dir
  app:
    name: app
    type: dir
  handler:
    nane: handler
    type: dir
  provider:
    name: provider
    type: dir
  server:
    name: server
    type: dir
  test:
    name: test
    type: dir
  main:
    name: main.go
    type: file
  