name: Go

on:
  push:
    branches: 
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --verbose
        skip-go-installation: true

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    # TODO: use make command
    - name: Get dependencies
      run: |
        go mod download

    - name: Test
      run: make test

    # TODO: use make command
    - name: Upload coverage to Codecov
      run: |
        bash <(curl -s https://codecov.io/bash)

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    # TODO: use make command
    - name: Get dependencies
      run: |
        go mod download

    # TODO: use make command
    - name: Build
      run: go build -v ./...
